// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnwSCZehca7S6ifUwzP3jqa_dWlen79Qg',
    appId: '1:1042384974674:web:703a7b72b03610c876008b',
    messagingSenderId: '1042384974674',
    projectId: 'flutter-firebase-projeto-470ed',
    authDomain: 'flutter-firebase-projeto-470ed.firebaseapp.com',
    storageBucket: 'flutter-firebase-projeto-470ed.firebasestorage.app',
    measurementId: 'G-9D7YW0FVTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7sqYYgA9Aze5GUwQywzzeGG4ew6KQoQ',
    appId: '1:1042384974674:android:aae881118eb43c5776008b',
    messagingSenderId: '1042384974674',
    projectId: 'flutter-firebase-projeto-470ed',
    storageBucket: 'flutter-firebase-projeto-470ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4Lg3wT_NV6lRYWBYyOKb_VjMPAm5GFI',
    appId: '1:1042384974674:ios:e74e32dca603cdbc76008b',
    messagingSenderId: '1042384974674',
    projectId: 'flutter-firebase-projeto-470ed',
    storageBucket: 'flutter-firebase-projeto-470ed.firebasestorage.app',
    iosBundleId: 'br.com.alura.flutterFirebaseAuthentication',
  );

}